swagger: '2.0'
info:
  version: 0.0.1
  title: DataMiningCloud Engine Service
  description: An API specification of DataMiningCloud Engine service based on swagger-2.0 specification
  contact:
    name: DataMiningCloud API team
    email: aid666@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
basePath: /engine
schemes:
  - http
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:

  /algorithms:
    get:
      tags:
      - Algorithms
      summary: Search processers metdata.
      description: Processers, it is actually execute code of any process flow. But this processer do not keep any model or paramter.
      parameters:
      - in: query
        name: catalog
        type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProcesserAlgorithm'

  /ad_hoc:
    post:
      tags:
      - Ad_hoc
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ProcessAdhocExe'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProcessMetadata'

  /ad_hoc/{exeKey}:
    get:
      tags:
      - Ad_hoc
      parameters:
      - name: exeKey
        in: path
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProcessMetadata'

  /flow:
    get:
      tags:
      - Flow
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProcessFlowMetadata'
    post:
      tags:
      - Flow
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/ProcessFlow'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProcessFlowMetadata'

  /flow/{flowKey}:
    get:
      tags:
      - Flow
      parameters:
      - name: flowKey
        in: path
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProcessFlowMetadata'

  /flow/{flowKey}/processes:
    get:
      tags:
      - Flow
      - Processes
      parameters:
      - name: flowKey
        in: path
        type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProcessMetadata'
    post:
      tags:
      - Flow
      - Processes
      parameters:
      - name: flowKey
        in: path
        type: string
      - name: body
        in: body
        schema:
          $ref: '#/definitions/DMData'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProcessMetadata'


  /flow/{flowKey}/processes/{procKey}:
    get:
      tags:
      - Flow
      - Processes
      parameters:
      - name: flowKey
        in: path
        type: string
      - name: procKey
        in: path
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProcessMetadata'
    delete:
      tags:
      - Flow
      - Processes
      parameters:
      - name: flowKey
        in: path
        type: string
      - name: procKey
        in: path
        type: string
      responses:
        204:
          description: OK

  /processes/{resultKey}:
    get:
      tags:
      - Processes
      parameters:
      - name: resultKey
        in: path
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ProcessStatus'

  /processes/{resultKey}/result:
    get:
      tags:
      - Processes
      parameters:
        - name: resultKey
          in: path
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Process'

definitions:
  Domain:
    properties:
      name:
        type: string
      date:
        description: The domain in differnent date may different, think about the change of computer brand from 1995 to 2015 .
        type: string
      parentDomain:
        $ref: '#/definitions/Domain'

  DMData:
    properties:
      key:
        type: string
      data:
        type: array
        items:
         $ref: '#/definitions/ColumnData'

  ColumnData:
    properties:
      attribute:
        $ref: '#/definitions/Attribute'
      data:
        type: array
        items:
          type: string

  DataInfor:
    properties:
      name:
        type: string
      domain:
        $ref: '#/definitions/Domain'

  Attribute:
    properties:
      name:
        type: string
      type:
        type: string
      format:
        type: string
      dataInfor:
        $ref: '#/definitions/DataInfor'

  ProcessMetadata:
    properties:
      key:
        type: string
      status:
        type: string

  ProcessStatus:
    properties:
      key:
        type: string
      status:
        type: string

  Process:
    properties:
      key:
        type: string
      inputData:
        $ref: '#/definitions/DMData'
      outputData:
        $ref: '#/definitions/DMData'
      errors:
        type: array
        items:
          type: string
      warnings:
        type: array
        items:
          type: string
      logs:
        type: array
        items:
          type: string

  ProcesserAlgorithm:
    properties:
      key:
        type: string
      name:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          type: string
      catalog:
        description: The catelog path of the trainer, classifier.decisionTree.id3
        type: string

  ProcessAdhocExe:
    properties:
      key:
        type: string

  ProcessFlow:
    properties:
      key:
        type: string

  ProcessFlowMetadata:
    properties:
      key:
        type: string
